// Code samples — small, faithful conversions for hero loop + gallery
window.SAMPLES = [
  {
    id: "button",
    title: "Sign-in button",
    desc: "Button with size, color & event",
    pairs: [
      {
        from: "JavaFX",
        ext: ".java",
        code: [
          { t: "/* Java — JavaFX */", c: "tok-c" },
          { t: "Button " },
          { t: "login", c: "tok-f" },
          { t: " = " },
          { t: "new", c: "tok-k" },
          { t: " " },
          { t: "Button", c: "tok-t" },
          { t: "(" },
          { t: '"Sign in"', c: "tok-s" },
          { t: ");\n" },
          { t: "login.setPrefSize(", c: "tok-p" },
          { t: "180", c: "tok-n" },
          { t: ", " },
          { t: "40", c: "tok-n" },
          { t: ");\n" },
          { t: "login.setStyle(\n" },
          { t: "  \"-fx-background-color: #5b5bff;\"", c: "tok-s" },
          { t: "\n  + " },
          { t: "\"-fx-text-fill: white;\"", c: "tok-s" },
          { t: ");\n" },
          { t: "login.setOnAction(e -> " },
          { t: "doLogin", c: "tok-f" },
          { t: "());" }
        ]
      },
      {
        from: "WinForms",
        ext: ".cs",
        code: [
          { t: "// C# — WinForms", c: "tok-c" },
          { t: "\n" },
          { t: "Button", c: "tok-t" },
          { t: " " },
          { t: "login", c: "tok-f" },
          { t: " = " },
          { t: "new", c: "tok-k" },
          { t: " " },
          { t: "Button", c: "tok-t" },
          { t: "();\n" },
          { t: "login.Text = " },
          { t: '"Sign in"', c: "tok-s" },
          { t: ";\n" },
          { t: "login.Size = " },
          { t: "new", c: "tok-k" },
          { t: " " },
          { t: "Size", c: "tok-t" },
          { t: "(" },
          { t: "180", c: "tok-n" },
          { t: ", " },
          { t: "40", c: "tok-n" },
          { t: ");\n" },
          { t: "login.BackColor = Color.FromArgb(" },
          { t: "91", c: "tok-n" },
          { t: ", " },
          { t: "91", c: "tok-n" },
          { t: ", " },
          { t: "255", c: "tok-n" },
          { t: ");\n" },
          { t: "login.ForeColor = Color.White;\n" },
          { t: "login.Click += (s, e) => " },
          { t: "DoLogin", c: "tok-f" },
          { t: "();" }
        ]
      },
      {
        from: "Tkinter",
        ext: ".py",
        code: [
          { t: "# Python — Tkinter", c: "tok-c" },
          { t: "\n" },
          { t: "login", c: "tok-f" },
          { t: " = tk." },
          { t: "Button", c: "tok-t" },
          { t: "(\n" },
          { t: "  text=" },
          { t: '"Sign in"', c: "tok-s" },
          { t: ",\n" },
          { t: "  bg=" },
          { t: '"#5b5bff"', c: "tok-s" },
          { t: ", fg=" },
          { t: '"white"', c: "tok-s" },
          { t: ",\n" },
          { t: "  width=" },
          { t: "20", c: "tok-n" },
          { t: ", height=" },
          { t: "2", c: "tok-n" },
          { t: ",\n" },
          { t: "  command=" },
          { t: "do_login", c: "tok-f" },
          { t: "\n)" }
        ]
      },
      {
        from: "ImGUI",
        ext: ".cpp",
        code: [
          { t: "// C++ — Dear ImGUI", c: "tok-c" },
          { t: "\n" },
          { t: "ImGui::PushStyleColor(\n" },
          { t: "  ImGuiCol_Button,\n" },
          { t: "  IM_COL32(" },
          { t: "91", c: "tok-n" },
          { t: ", " },
          { t: "91", c: "tok-n" },
          { t: ", " },
          { t: "255", c: "tok-n" },
          { t: ", " },
          { t: "255", c: "tok-n" },
          { t: ")\n);\n" },
          { t: "if", c: "tok-k" },
          { t: " (ImGui::Button(" },
          { t: '"Sign in"', c: "tok-s" },
          { t: ", { " },
          { t: "180", c: "tok-n" },
          { t: ", " },
          { t: "40", c: "tok-n" },
          { t: " })) {\n" },
          { t: "  " },
          { t: "doLogin", c: "tok-f" },
          { t: "();\n" },
          { t: "}" }
        ]
      }
    ]
  },
  {
    id: "form",
    title: "Login form",
    desc: "Labels, fields, password",
    pairs: [
      {
        from: "JavaFX",
        ext: ".java",
        code: [
          { t: "VBox", c: "tok-t" },
          { t: " " },
          { t: "form", c: "tok-f" },
          { t: " = " },
          { t: "new", c: "tok-k" },
          { t: " " },
          { t: "VBox", c: "tok-t" },
          { t: "(" },
          { t: "12", c: "tok-n" },
          { t: ");\n" },
          { t: "Label", c: "tok-t" },
          { t: " " },
          { t: "userLbl", c: "tok-f" },
          { t: " = " },
          { t: "new", c: "tok-k" },
          { t: " " },
          { t: "Label", c: "tok-t" },
          { t: "(" },
          { t: '"Username"', c: "tok-s" },
          { t: ");\n" },
          { t: "TextField", c: "tok-t" },
          { t: " " },
          { t: "userFld", c: "tok-f" },
          { t: " = " },
          { t: "new", c: "tok-k" },
          { t: " " },
          { t: "TextField", c: "tok-t" },
          { t: "();\n" },
          { t: "PasswordField", c: "tok-t" },
          { t: " " },
          { t: "pwdFld", c: "tok-f" },
          { t: " = " },
          { t: "new", c: "tok-k" },
          { t: " " },
          { t: "PasswordField", c: "tok-t" },
          { t: "();\n" },
          { t: "form.getChildren().addAll(\n" },
          { t: "  userLbl, userFld, pwdFld);" }
        ]
      },
      {
        from: "WinForms",
        ext: ".cs",
        code: [
          { t: "FlowLayoutPanel", c: "tok-t" },
          { t: " " },
          { t: "form", c: "tok-f" },
          { t: " = " },
          { t: "new", c: "tok-k" },
          { t: "();\n" },
          { t: "form.FlowDirection = FlowDirection.TopDown;\n\n" },
          { t: "Label", c: "tok-t" },
          { t: " " },
          { t: "userLbl", c: "tok-f" },
          { t: " = " },
          { t: "new", c: "tok-k" },
          { t: " " },
          { t: "Label", c: "tok-t" },
          { t: "();\n" },
          { t: "userLbl.Text = " },
          { t: '"Username"', c: "tok-s" },
          { t: ";\n" },
          { t: "TextBox", c: "tok-t" },
          { t: " " },
          { t: "userFld", c: "tok-f" },
          { t: " = " },
          { t: "new", c: "tok-k" },
          { t: "();\n" },
          { t: "MaskedTextBox", c: "tok-t" },
          { t: " " },
          { t: "pwdFld", c: "tok-f" },
          { t: " = " },
          { t: "new", c: "tok-k" },
          { t: "();\n" },
          { t: "pwdFld.PasswordChar = " },
          { t: "'•'", c: "tok-s" },
          { t: ";\n" },
          { t: "form.Controls.AddRange(\n" },
          { t: "  new Control[] { userLbl, userFld, pwdFld });" }
        ]
      }
    ]
  },
  {
    id: "colors",
    title: "Theme colors",
    desc: "Named, hex, rgb — all normalized",
    pairs: [
      {
        from: "JavaFX",
        ext: ".java",
        code: [
          { t: "// hex, named, and rgb() — UIPorter normalizes all three", c: "tok-c" },
          { t: "\n" },
          { t: "card.setStyle(\n" },
          { t: '  "-fx-background-color: #1f1f2e;"', c: "tok-s" },
          { t: "\n  + " },
          { t: '"-fx-border-color: cornflowerblue;"', c: "tok-s" },
          { t: "\n  + " },
          { t: '"-fx-text-fill: rgb(232, 232, 245);"', c: "tok-s" },
          { t: "\n);" }
        ]
      },
      {
        from: "WinForms",
        ext: ".cs",
        code: [
          { t: "// every color round-trips losslessly", c: "tok-c" },
          { t: "\n" },
          { t: "card.BackColor = Color.FromArgb(" },
          { t: "31", c: "tok-n" },
          { t: ", " },
          { t: "31", c: "tok-n" },
          { t: ", " },
          { t: "46", c: "tok-n" },
          { t: ");\n" },
          { t: "card.BorderStyle = BorderStyle.FixedSingle;\n" },
          { t: "card.ForeColor = Color.FromArgb(" },
          { t: "232", c: "tok-n" },
          { t: ", " },
          { t: "232", c: "tok-n" },
          { t: ", " },
          { t: "245", c: "tok-n" },
          { t: ");" }
        ]
      }
    ]
  },
  {
    id: "layout",
    title: "Grid layout",
    desc: "Rows, columns, gaps — preserved",
    pairs: [
      {
        from: "JavaFX",
        ext: ".java",
        code: [
          { t: "GridPane", c: "tok-t" },
          { t: " " },
          { t: "grid", c: "tok-f" },
          { t: " = " },
          { t: "new", c: "tok-k" },
          { t: " " },
          { t: "GridPane", c: "tok-t" },
          { t: "();\n" },
          { t: "grid.setHgap(" },
          { t: "12", c: "tok-n" },
          { t: ");\n" },
          { t: "grid.setVgap(" },
          { t: "8", c: "tok-n" },
          { t: ");\n" },
          { t: "grid.add(" },
          { t: "nameLbl", c: "tok-f" },
          { t: ", " },
          { t: "0", c: "tok-n" },
          { t: ", " },
          { t: "0", c: "tok-n" },
          { t: ");\n" },
          { t: "grid.add(" },
          { t: "nameFld", c: "tok-f" },
          { t: ", " },
          { t: "1", c: "tok-n" },
          { t: ", " },
          { t: "0", c: "tok-n" },
          { t: ");\n" },
          { t: "grid.add(" },
          { t: "saveBtn", c: "tok-f" },
          { t: ", " },
          { t: "1", c: "tok-n" },
          { t: ", " },
          { t: "1", c: "tok-n" },
          { t: ");" }
        ]
      },
      {
        from: "WinForms",
        ext: ".cs",
        code: [
          { t: "TableLayoutPanel", c: "tok-t" },
          { t: " " },
          { t: "grid", c: "tok-f" },
          { t: " = " },
          { t: "new", c: "tok-k" },
          { t: "();\n" },
          { t: "grid.ColumnCount = " },
          { t: "2", c: "tok-n" },
          { t: ";\n" },
          { t: "grid.RowCount = " },
          { t: "2", c: "tok-n" },
          { t: ";\n" },
          { t: "grid.Margin = " },
          { t: "new", c: "tok-k" },
          { t: " " },
          { t: "Padding", c: "tok-t" },
          { t: "(" },
          { t: "8", c: "tok-n" },
          { t: ", " },
          { t: "8", c: "tok-n" },
          { t: ", " },
          { t: "8", c: "tok-n" },
          { t: ", " },
          { t: "8", c: "tok-n" },
          { t: ");\n" },
          { t: "grid.Controls.Add(nameLbl, " },
          { t: "0", c: "tok-n" },
          { t: ", " },
          { t: "0", c: "tok-n" },
          { t: ");\n" },
          { t: "grid.Controls.Add(nameFld, " },
          { t: "1", c: "tok-n" },
          { t: ", " },
          { t: "0", c: "tok-n" },
          { t: ");\n" },
          { t: "grid.Controls.Add(saveBtn, " },
          { t: "1", c: "tok-n" },
          { t: ", " },
          { t: "1", c: "tok-n" },
          { t: ");" }
        ]
      }
    ]
  }
];
