import javafx.application.Application;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.collections.ObservableList;
import javafx.scene.image.*;
import javafx.scene.layout.*;
import javafx.scene.text.Font;
import javafx.stage.Stage;
import javafx.scene.shape.*;
import javafx.scene.paint.Color;
import javafx.scene.chart.*;
import javafx.scene.canvas.Canvas;

public class ConvertedApp extends Application {
    @Override
    public void start(Stage stage) {

        StackPane root = new StackPane();
        Canvas canvas = new Canvas();
        BorderPane mainLayout = new BorderPane();
        VBox sidebar = new VBox();
        Label sidebar_c0 = new Label();
        Button sidebar_c1 = new Button();
        Button sidebar_c2 = new Button();
        Button sidebar_c3 = new Button();
        Button sidebar_c4 = new Button();
        Button sidebar_c5 = new Button();
        Button sidebar_c6 = new Button();
        Region sidebar_c7 = new Region();
        VBox sidebar_c8 = new VBox();
        Label sidebar_c8_c0 = new Label();
        Label sidebar_c8_c1 = new Label();
        Button sidebar_c8_c2 = new Button();
        ScrollPane scrollPane = new ScrollPane();
        VBox content = new VBox();
        HBox createHeader_header = new HBox();
        Label createHeader_title = new Label();
        Region createHeader_spacer = new Region();
        TextField createHeader_search = new TextField();
        Circle createHeader_avatar = new Circle();
        HBox statsRow = new HBox();
        VBox createStatCard_card = new VBox();
        Label createStatCard_lblTitle = new Label();
        Label createStatCard_lblVal = new Label();
        Label createStatCard_lblTrend = new Label();
        Rectangle createStatCard_bar = new Rectangle();
        VBox createStatCard_card_1 = new VBox();
        Label createStatCard_card_1_c0 = new Label();
        Label createStatCard_card_1_c1 = new Label();
        Label createStatCard_card_1_c2 = new Label();
        Rectangle createStatCard_card_1_c3 = new Rectangle();
        VBox createStatCard_card_2 = new VBox();
        Label createStatCard_card_2_c0 = new Label();
        Label createStatCard_card_2_c1 = new Label();
        Label createStatCard_card_2_c2 = new Label();
        Rectangle createStatCard_card_2_c3 = new Rectangle();
        VBox createStatCard_card_3 = new VBox();
        Label createStatCard_card_3_c0 = new Label();
        Label createStatCard_card_3_c1 = new Label();
        Label createStatCard_card_3_c2 = new Label();
        Rectangle createStatCard_card_3_c3 = new Rectangle();
        HBox chartRow = new HBox();
        StackPane createLineChart_container = new StackPane();
        CategoryAxis createLineChart_lineChartX = new CategoryAxis();
        NumberAxis createLineChart_lineChartY = new NumberAxis();
        LineChart<String, Number> createLineChart_lineChart = new LineChart<>(createLineChart_lineChartX, createLineChart_lineChartY);
        StackPane createPieChart_container = new StackPane();
        PieChart createPieChart_pieChart = new PieChart();
        HBox bottomRow = new HBox();
        VBox createProjectTable_container = new VBox();
        Label createProjectTable_title = new Label();
        TableView createProjectTable_table = new TableView();
        VBox createControlsPanel_container = new VBox();
        Label createControlsPanel_title = new Label();
        Label createControlsPanel_sliderVal = new Label();
        Slider createControlsPanel_slider = new Slider();
        CheckBox createControlsPanel_c1 = new CheckBox();
        CheckBox createControlsPanel_c2 = new CheckBox();
        CheckBox createControlsPanel_c3 = new CheckBox();
        Button createControlsPanel_actionBtn = new Button();

        root.setStyle("-fx-background-color: #0b090a;");
        root.setPrefSize(1280, 850);
        mainLayout.setPadding(new Insets(20));
        sidebar.getStyleClass().addAll("glass-panel");
        sidebar.setPrefWidth(240);
        sidebar.setSpacing(15);
        sidebar.setPadding(new Insets(30, 15, 30, 15));
        sidebar_c0.setText("NEBULA");
        sidebar_c0.setStyle("-fx-text-fill: white; -fx-font-size: 28pt; -fx-font-weight: bold;");
        sidebar_c0.setPadding(new Insets(0, 0, 30, 0));
        sidebar_c1.setText("Dashboard");
        sidebar_c2.setText("Analytics");
        sidebar_c3.setText("Project Map");
        sidebar_c4.setText("Team");
        sidebar_c5.setText("Cloud Storage");
        sidebar_c6.setText("Settings");
        sidebar_c8.getStyleClass().addAll("upgrade-card");
        sidebar_c8.setSpacing(10);
        sidebar_c8_c0.setText("PRO PLAN");
        sidebar_c8_c1.setText("Get unlimited access to AI tools");
        sidebar_c8_c2.setText("Upgrade Now");
        scrollPane.setStyle("-fx-background-color: transparent; -fx-background: transparent;");
        scrollPane.setPadding(new Insets(0, 0, 0, 20));
        content.setSpacing(25);
        content.setPadding(new Insets(0, 20, 0, 0));
        createHeader_header.setAlignment(Pos.CENTER_LEFT);
        createHeader_header.setSpacing(20);
        createHeader_title.setText("Enterprise Overview");
        createHeader_title.setStyle("-fx-text-fill: white; -fx-font-size: 24pt; -fx-font-weight: bold;");
        HBox.setHgrow(createHeader_spacer, javafx.scene.layout.Priority.ALWAYS);
        createHeader_search.getStyleClass().addAll("search-box");
        createHeader_search.setPromptText("Search anything...");
        createHeader_search.setPrefWidth(300);
        createHeader_avatar.setRadius(20);
        createHeader_avatar.setFill(javafx.scene.paint.Color.web("#7209b7"));
        createHeader_avatar.setStroke(javafx.scene.paint.Color.WHITE);
        createHeader_avatar.setStrokeWidth(2);
        statsRow.setSpacing(20);
        createStatCard_card.getStyleClass().addAll("glass-panel");
        createStatCard_card.setPrefWidth(280);
        createStatCard_card.setSpacing(8);
        createStatCard_card.setPadding(new Insets(20));
        createStatCard_lblTitle.setText("Total Revenue");
        createStatCard_lblTitle.setStyle("-fx-text-fill: #adb5bd; -fx-font-size: 14pt;");
        createStatCard_lblVal.setText("$124,592");
        createStatCard_lblVal.setStyle("-fx-text-fill: white; -fx-font-size: 24pt; -fx-font-weight: bold;");
        createStatCard_lblTrend.setText("+12.5%");
        createStatCard_lblTrend.setStyle("-fx-font-weight: bold;");
        createStatCard_bar.setWidth(40);
        createStatCard_bar.setHeight(4);
        createStatCard_card_1.getStyleClass().addAll("glass-panel");
        createStatCard_card_1.setPrefWidth(280);
        createStatCard_card_1.setSpacing(8);
        createStatCard_card_1.setPadding(new Insets(20));
        createStatCard_card_1_c0.setText("Active Users");
        createStatCard_card_1_c0.setStyle("-fx-text-fill: #adb5bd; -fx-font-size: 14pt;");
        createStatCard_card_1_c1.setText("12,843");
        createStatCard_card_1_c1.setStyle("-fx-text-fill: white; -fx-font-size: 24pt; -fx-font-weight: bold;");
        createStatCard_card_1_c2.setText("+5.2%");
        createStatCard_card_1_c2.setStyle("-fx-font-weight: bold;");
        createStatCard_card_1_c3.setWidth(40);
        createStatCard_card_1_c3.setHeight(4);
        createStatCard_card_2.getStyleClass().addAll("glass-panel");
        createStatCard_card_2.setPrefWidth(280);
        createStatCard_card_2.setSpacing(8);
        createStatCard_card_2.setPadding(new Insets(20));
        createStatCard_card_2_c0.setText("Conversion");
        createStatCard_card_2_c0.setStyle("-fx-text-fill: #adb5bd; -fx-font-size: 14pt;");
        createStatCard_card_2_c1.setText("3.8%");
        createStatCard_card_2_c1.setStyle("-fx-text-fill: white; -fx-font-size: 24pt; -fx-font-weight: bold;");
        createStatCard_card_2_c2.setText("-1.1%");
        createStatCard_card_2_c2.setStyle("-fx-font-weight: bold;");
        createStatCard_card_2_c3.setWidth(40);
        createStatCard_card_2_c3.setHeight(4);
        createStatCard_card_3.getStyleClass().addAll("glass-panel");
        createStatCard_card_3.setPrefWidth(280);
        createStatCard_card_3.setSpacing(8);
        createStatCard_card_3.setPadding(new Insets(20));
        createStatCard_card_3_c0.setText("System Load");
        createStatCard_card_3_c0.setStyle("-fx-text-fill: #adb5bd; -fx-font-size: 14pt;");
        createStatCard_card_3_c1.setText("42%");
        createStatCard_card_3_c1.setStyle("-fx-text-fill: white; -fx-font-size: 24pt; -fx-font-weight: bold;");
        createStatCard_card_3_c2.setText("Stable");
        createStatCard_card_3_c2.setStyle("-fx-font-weight: bold;");
        createStatCard_card_3_c3.setWidth(40);
        createStatCard_card_3_c3.setHeight(4);
        chartRow.setSpacing(20);
        createLineChart_container.getStyleClass().addAll("glass-panel");
        createLineChart_container.setPadding(new Insets(10));
        HBox.setHgrow(createLineChart_container, javafx.scene.layout.Priority.ALWAYS);
        createPieChart_container.getStyleClass().addAll("glass-panel");
        createPieChart_container.setPadding(new Insets(10));
        createPieChart_pieChart.setPrefWidth(350);
        bottomRow.setSpacing(20);
        createProjectTable_container.getStyleClass().addAll("glass-panel");
        createProjectTable_container.setSpacing(15);
        createProjectTable_container.setPadding(new Insets(20));
        HBox.setHgrow(createProjectTable_container, javafx.scene.layout.Priority.ALWAYS);
        createProjectTable_title.setText("Recent Projects");
        createProjectTable_title.setStyle("-fx-text-fill: white; -fx-font-size: 18pt; -fx-font-weight: bold;");
        createProjectTable_table.setPrefHeight(250);
        createProjectTable_table.setMaxHeight(250);
        createControlsPanel_container.getStyleClass().addAll("glass-panel");
        createControlsPanel_container.setPrefWidth(350);
        createControlsPanel_container.setSpacing(20);
        createControlsPanel_container.setPadding(new Insets(20));
        createControlsPanel_title.setText("System Controls");
        createControlsPanel_title.setStyle("-fx-text-fill: white; -fx-font-size: 18pt; -fx-font-weight: bold;");
        createControlsPanel_sliderVal.setText("Network Throttle: 75%");
        createControlsPanel_sliderVal.setStyle("-fx-text-fill: #adb5bd;");
        createControlsPanel_slider.setMin(0);
        createControlsPanel_slider.setMax(100);
        createControlsPanel_slider.setValue(75);
        createControlsPanel_c1.setText("Enable AI Optimization");
        createControlsPanel_c1.setSelected(true);
        createControlsPanel_c2.setText("Hardware Acceleration");
        createControlsPanel_c3.setText("Auto-Scale Nodes");
        createControlsPanel_actionBtn.setText("DEPLOY SYSTEM");
        createControlsPanel_actionBtn.getStyleClass().addAll("action-btn");

        root.getChildren().add(canvas);
        root.getChildren().add(mainLayout);
        mainLayout.setLeft(sidebar);
        sidebar.getChildren().add(sidebar_c0);
        sidebar.getChildren().add(sidebar_c1);
        sidebar.getChildren().add(sidebar_c2);
        sidebar.getChildren().add(sidebar_c3);
        sidebar.getChildren().add(sidebar_c4);
        sidebar.getChildren().add(sidebar_c5);
        sidebar.getChildren().add(sidebar_c6);
        sidebar.getChildren().add(sidebar_c7);
        sidebar.getChildren().add(sidebar_c8);
        sidebar_c8.getChildren().add(sidebar_c8_c0);
        sidebar_c8.getChildren().add(sidebar_c8_c1);
        sidebar_c8.getChildren().add(sidebar_c8_c2);
        mainLayout.setCenter(scrollPane);
        scrollPane.setContent(content);
        content.getChildren().add(createHeader_header);
        createHeader_header.getChildren().add(createHeader_title);
        createHeader_header.getChildren().add(createHeader_spacer);
        createHeader_header.getChildren().add(createHeader_search);
        createHeader_header.getChildren().add(createHeader_avatar);
        content.getChildren().add(statsRow);
        statsRow.getChildren().add(createStatCard_card);
        createStatCard_card.getChildren().add(createStatCard_lblTitle);
        createStatCard_card.getChildren().add(createStatCard_lblVal);
        createStatCard_card.getChildren().add(createStatCard_lblTrend);
        createStatCard_card.getChildren().add(createStatCard_bar);
        statsRow.getChildren().add(createStatCard_card_1);
        createStatCard_card_1.getChildren().add(createStatCard_card_1_c0);
        createStatCard_card_1.getChildren().add(createStatCard_card_1_c1);
        createStatCard_card_1.getChildren().add(createStatCard_card_1_c2);
        createStatCard_card_1.getChildren().add(createStatCard_card_1_c3);
        statsRow.getChildren().add(createStatCard_card_2);
        createStatCard_card_2.getChildren().add(createStatCard_card_2_c0);
        createStatCard_card_2.getChildren().add(createStatCard_card_2_c1);
        createStatCard_card_2.getChildren().add(createStatCard_card_2_c2);
        createStatCard_card_2.getChildren().add(createStatCard_card_2_c3);
        statsRow.getChildren().add(createStatCard_card_3);
        createStatCard_card_3.getChildren().add(createStatCard_card_3_c0);
        createStatCard_card_3.getChildren().add(createStatCard_card_3_c1);
        createStatCard_card_3.getChildren().add(createStatCard_card_3_c2);
        createStatCard_card_3.getChildren().add(createStatCard_card_3_c3);
        content.getChildren().add(chartRow);
        chartRow.getChildren().add(createLineChart_container);
        createLineChart_container.getChildren().add(createLineChart_lineChart);
        chartRow.getChildren().add(createPieChart_container);
        createPieChart_container.getChildren().add(createPieChart_pieChart);
        content.getChildren().add(bottomRow);
        bottomRow.getChildren().add(createProjectTable_container);
        createProjectTable_container.getChildren().add(createProjectTable_title);
        createProjectTable_container.getChildren().add(createProjectTable_table);
        bottomRow.getChildren().add(createControlsPanel_container);
        createControlsPanel_container.getChildren().add(createControlsPanel_title);
        createControlsPanel_container.getChildren().add(createControlsPanel_sliderVal);
        createControlsPanel_container.getChildren().add(createControlsPanel_slider);
        createControlsPanel_container.getChildren().add(createControlsPanel_c1);
        createControlsPanel_container.getChildren().add(createControlsPanel_c2);
        createControlsPanel_container.getChildren().add(createControlsPanel_c3);
        createControlsPanel_container.getChildren().add(createControlsPanel_actionBtn);

        Scene scene = new Scene(root, 1280, 850);
        scene.getStylesheets().add("data:text/css,.glass-panel {    -fx-background-color: rgba(255, 255, 255, 0.05);    -fx-background-radius: 15;    -fx-border-color: rgba(255, 255, 255, 0.1);    -fx-border-radius: 15;    -fx-border-width: 1;}.sidebar-btn {    -fx-background-color: transparent;    -fx-text-fill: #adb5bd;    -fx-alignment: CENTER_LEFT;    -fx-padding: 12 20;    -fx-font-size: 14;    -fx-cursor: hand;    -fx-background-radius: 10;}.sidebar-btn:hover {    -fx-background-color: rgba(255, 255, 255, 0.08);    -fx-text-fill: white;}.sidebar-btn-active {    -fx-background-color: #7209b7;    -fx-text-fill: white;}.search-box {    -fx-background-color: rgba(255, 255, 255, 0.08);    -fx-background-radius: 20;    -fx-text-fill: white;    -fx-padding: 8 15;    -fx-border-color: transparent;}.upgrade-card {    -fx-background-color: linear-gradient(to bottom right, #7209b7, #3f37c9);    -fx-background-radius: 15;    -fx-padding: 20;}.upgrade-card Label {    -fx-text-fill: white;}.upgrade-card Button {    -fx-background-color: white;    -fx-text-fill: #7209b7;    -fx-font-weight: bold;    -fx-background-radius: 10;    -fx-padding: 8 15;}.table-view {    -fx-background-color: transparent;    -fx-base: transparent;    -fx-control-inner-background: transparent;}.table-view .column-header-background {    -fx-background-color: rgba(255, 255, 255, 0.05);}.table-view .column-header {    -fx-background-color: transparent;}.table-view .cell {    -fx-text-fill: white;    -fx-border-color: transparent;}.table-row-cell:odd {    -fx-background-color: rgba(255, 255, 255, 0.02);}.progress-bar {    -fx-accent: #4cc9f0;}.progress-bar .track {    -fx-background-color: rgba(255, 255, 255, 0.1);    -fx-background-radius: 5;}.check-box {    -fx-text-fill: #adb5bd;}.check-box .box {    -fx-background-color: rgba(255, 255, 255, 0.1);}.action-btn {    -fx-background-color: #f72585;    -fx-text-fill: white;    -fx-font-weight: bold;    -fx-padding: 15;    -fx-background-radius: 10;    -fx-cursor: hand;}.chart-plot-background {    -fx-background-color: transparent;}.chart-vertical-grid-lines, .chart-horizontal-grid-lines {    -fx-stroke: rgba(255, 255, 255, 0.05);}.axis {    -fx-tick-label-fill: #adb5bd;}.default-color0.chart-series-line {    -fx-stroke: #7209b7;}.default-color0.chart-line-symbol {    -fx-background-color: #7209b7, white;}");
        stage.setScene(scene);
        stage.setTitle("App");
        stage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}
